Add SoC information in machines where it is missing
Freescale/meta-freescale pull request #1140
Opened 2022-07-19 21:19 UTC by Ossanes

Signed-off-by: Vinicius Aquino <vinicius.aquino@ossystems.com.br>

2022-07-19 21:44 UTC, otavio requested changes

2022-07-19 21:44 UTC, otavio commented on conf/machine/imx8dx-mek.conf
> +#@SOC: i.MX8DX
Please list the machine files you are changing in the commit log.

2022-07-25 22:40 UTC, otavio approved these changes

2022-07-26 15:39 UTC, angolini approved these changes

2022-07-26 16:30 UTC, merged