imx-gpu-viv: Do not require wayland on i.MX8.
Freescale/meta-freescale pull request #1212
Opened 2022-09-16 13:36 UTC by LocutusOfBorg

Do not require wayland on i.MX8.

This is a cherry-pick with changes of commit 14a48c1d546323ebecde37f25162bc69c59e3096 of meta-digi https://github.com/digi-embedded/meta-digi/commit/14a48c1d546323ebecde37f25162bc69c59e3096 with this commit message:
From 14a48c1d546323ebecde37f25162bc69c59e3096 Mon Sep 17 00:00:00 2001
From: Arturo Buzarra <arturo.buzarra@digi.com>
Date: Mon, 27 Apr 2020 19:51:16 +0200
Subject: [PATCH] imx-gpu-viv: remove wayland as a requirement for i.MX8
 platforms

Based on commit ed2c4974 ("imx-gpu-viv: remove wayland as a requirement for i.MX8 platforms"), this commit removes the requeriment of wayland as a backend for the i.MX8 platforms to build framebuffer images.

https://jira.digi.com/browse/DEL-7013

Signed-off-by: Arturo Buzarra <arturo.buzarra@digi.com>

This is not needed to depend on a full wayland stack when the library is just requesting one single wayland library

readelf -d libgbm-imx/usr/lib/libgbm_viv.so
 0x0000000000000001 (NEEDED)             Shared library: [libwayland-server.so.0]

see: https://www.yoctoproject.org/pipermail/meta-freescale/2018-September/023340.html

Reported-by: Paolo Doz <paolo.doz@abinsula.com>
Reported-by: Francesco Loi <francesco.loi@abinsula.com>
Signed-off-by: Gianfranco Costamagna <costamagnagianfranco@yahoo.it>

2022-09-16 13:43 UTC, otavio requested changes
Please adjust your commit log as there is an extra new line in the first line.

@thochstein, please confirm internally with Prabu?

2022-09-16 14:29 UTC, LocutusOfBorg commented
@otavio done thanks

2022-09-16 15:11 UTC, otavio approved these changes

2022-09-16 16:33 UTC, LocutusOfBorg commented
This change was tested on one of our imx8 boarda, with a qt app built to output on framebuffer and didn't error out
This change permits to avoid wayland binaries, even tho we can't avoid libwayland

We did save 5MB of compressed, and probably more than 10MB of disk space and lots of seconds gained of boot-time

2022-09-16 16:59 UTC, thochstein commented
Prabhu says we definitely require `libwayland`, but otherwise don't care about the rest of what might get pulled in for `wayland` distro feature.

Is your change complete? I get the following error using `fsl-framebuffer` distro:

```
| cp: cannot stat '/.../imx-gpu-viv/1_6.4.3.p4.2-aarch64-r0/imx-gpu-viv-6.4.3.p4.2-aarch64/gpu-core/usr/lib/fb/*': No such file or directory
```

2022-09-18 19:30 UTC, LocutusOfBorg commented
@thochstein MACHINE=?

2022-09-18 19:30 UTC, LocutusOfBorg commented
and which image are you building?

2022-09-19 11:08 UTC, LocutusOfBorg commented
well, I just found this:
find imx-gpu-viv-6.4.0.p2.4-aarch64/ -name "*fb*"
imx-gpu-viv-6.4.0.p2.4-aarch64/gpu-core/usr/lib/libVDK-fb.so
imx-gpu-viv-6.4.0.p2.4-aarch64/gpu-core/usr/lib/libvulkan-fb.so.1.1.3
imx-gpu-viv-6.4.0.p2.4-aarch64/gpu-core/usr/lib/pkgconfig/egl_linuxfb.pc
imx-gpu-viv-6.4.0.p2.4-aarch64/gpu-core/usr/lib/libGLESv2-fb.so
imx-gpu-viv-6.4.0.p2.4-aarch64/gpu-core/usr/lib/libEGL-fb.so
imx-gpu-viv-6.4.0.p2.4-aarch64/gpu-core/usr/lib/libGAL-fb.so
imx-gpu-viv-6.4.0.p2.4-aarch64/gpu-core/usr/lib/libvulkan-fb.so

while on new release:
find imx-gpu-viv-6.4.3.p4.2-aarch64/ -name "*fb*"
imx-gpu-viv-6.4.3.p4.2-aarch64/gpu-core/usr/include/vulkan/vulkan_directfb.h
imx-gpu-viv-6.4.3.p4.2-aarch64/gpu-core/usr/lib/pkgconfig/egl_linuxfb.pc


So, we are forced to 6.4.0 version if we want to use fb directly?

2022-09-19 11:08 UTC, closed without merging

2022-09-19 18:37 UTC, thochstein commented
Sorry, @LocutusOfBorg, we dropped this configuration. I am told it will likely work, but unfortunately it is not tested. I can make some modifications to the recipe if you want to try it?

2022-09-20 13:35 UTC, LocutusOfBorg commented
sure!