Fix the image/SDK generation for packages built for MACHINE_SOCARCH with MULTILIB support
Freescale/meta-freescale pull request #1213
Opened 2022-09-16 13:36 UTC by gderoire-hach

To reproduce the problem
Add to local.conf:
require conf/multilib.conf
MULTILIBS = "multilib:lib32"
DEFAULTTUNE:virtclass-multilib-lib32 = "armv7athf-neon-vfpv4" 
IMAGE_INSTALL_append = "lib32-libusb1"

Build image with:
'bitbake core-image-minimal'

The build will fail during do_rootfs/do_populate_sdk on lib32-wayland-protocols package

2022-09-16 13:57 UTC, otavio requested changes
I will reproduce this locally. In meanwhile, I'd like to ask you to rework the commit log. One suggestion:

```
classes/fsl-dynamic-packagearch: Add multilib support

Currently, the class doesn't support multilib image/SDK generation for packages
built for MACHINE_SOCARCH with MULTILIB support and this commit fixes this.

To reproduce the error, add to local.conf:

require conf/multilib.conf
MULTILIBS = "multilib:lib32"
DEFAULTTUNE:virtclass-multilib-lib32 = "armv7athf-neon-vfpv4"
IMAGE_INSTALL_append = "lib32-libusb1"

Build image with: 'bitbake core-image-minimal'

The build will fail during do_rootfs/do_populate_sdk on lib32-wayland-protocols package.
```

2022-09-29 07:19 UTC, gderoire-hach commented
Hello, 

Were you able to reproduce the issue on your side ?

2022-09-29 21:41 UTC, otavio reviewed
I couldn't reproduce the issue. Few questions:

- which machine did you use to reproduce it?
- did you use which branch?

![image](https://user-images.githubusercontent.com/25278/193147205-f738988d-20ae-4253-aab0-4c6fd28e1adf.png)

2022-09-30 07:28 UTC, gderoire-hach commented
Here is my local.conf generated with: "MACHINE=imx8dx-mek DISTRO=fslc-xwayland source ./setup-environment build"
```
MACHINE ??= 'imx8dx-mek'
DISTRO ?= 'fslc-xwayland'
EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
USER_CLASSES ?= "buildstats"
PATCHRESOLVE = "noop"
BB_DISKMON_DIRS ??= "\
    STOPTASKS,${TMPDIR},1G,100K \
    STOPTASKS,${DL_DIR},1G,100K \
    STOPTASKS,${SSTATE_DIR},1G,100K \
    STOPTASKS,/tmp,100M,100K \
    HALT,${TMPDIR},100M,1K \
    HALT,${DL_DIR},100M,1K \
    HALT,${SSTATE_DIR},100M,1K \
    HALT,/tmp,10M,1K"
PACKAGECONFIG:append:pn-qemu-system-native = " sdl"
CONF_VERSION = "2"

DL_DIR ?= "${BSPDIR}/downloads/"
ACCEPT_FSL_EULA = "1"

require conf/multilib.conf
MULTILIBS = "multilib:lib32"
DEFAULTTUNE:virtclass-multilib-lib32 = "armv7athf-neon"
IMAGE_INSTALL:append = "lib32-libusb1
```"

DEFAULTTUNE is a bit different and I have fixed the IMAGE_INSTALL_append into IMAGE_INSTALL:append

About the branch used, I have used the master at that time. I have tried again today master, but seems there is some incompatibilities between freescale-distro and langdale, so I have to investigate a bit.

2022-10-04 15:07 UTC, otavio commented
@gderoire-hach I fixed distro issue, can you check?

2022-10-05 13:06 UTC, gderoire-hach commented
@otavio,

Thanks for the fix.

I have rebuilt with master and still got the error:
```
Build Configuration:
BB_VERSION           = "2.2.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "aarch64-fslc-linux"
MACHINE              = "imx8dx-mek"
DISTRO               = "fslc-xwayland"
DISTRO_VERSION       = "4.1-snapshot-20221005"
TUNE_FEATURES        = "aarch64 armv8a crc cortexa35"
TARGET_FPU           = ""
meta
meta-poky            = "HEAD:5200799866b92259e855051112520006e1aaaac0"
meta-oe
meta-multimedia
meta-python          = "HEAD:9ab32b214b54a58baf49a725dddf1c720d4195d1"
meta-freescale       = "master:1b9f6007753bcd6e55fcff1f8b22c96c827b9e83"
meta-freescale-3rdparty = "HEAD:07c9d8e205caa3a41844d7f9086bdc88cfdff7a7"
meta-freescale-distro = "HEAD:27db351d186a0c8a9f7c4c0932df5b290f3a50f1"

Initialising tasks: 100% |####################################################################################################################################| Time: 0:00:11
Sstate summary: Wanted 1361 Local 0 Mirrors 0 Missed 1361 Current 709 (0% match, 34% complete)
Removing 121 stale sstate objects for arch x86_64: 100% |#####################################################################################################| Time: 0:00:01
Removing 286 stale sstate objects for arch imx8dx_mek: 100% |#################################################################################################| Time: 0:00:06
Removing 410 stale sstate objects for arch cortexa35: 100% |##################################################################################################| Time: 0:00:01
NOTE: Executing Tasks
Setscene tasks: 2070 of 2070
WARNING: optee-os-3.17.0.imx-r0 do_package_qa: QA Issue: File /usr/include/optee/export-user_ta_arm64/lib/libutils.a in package optee-os-staticdev contains reference to TMPDIR
File /usr/include/optee/export-user_ta_arm64/lib/libutee.a in package optee-os-staticdev contains reference to TMPDIR [buildpaths]
WARNING: linux-fslc-imx-5.15.67+gitAUTOINC+845d53f13a-r0 do_package_qa: QA Issue: File /usr/src/debug/linux-fslc-imx/5.15.67+gitAUTOINC+845d53f13a-r0/lib/oid_registry_data.c in package linux-fslc-imx-src contains reference to TMPDIR
File /usr/src/debug/linux-fslc-imx/5.15.67+gitAUTOINC+845d53f13a-r0/drivers/tty/vt/consolemap_deftbl.c in package linux-fslc-imx-src contains reference to TMPDIR
File /usr/src/debug/linux-fslc-imx/5.15.67+gitAUTOINC+845d53f13a-r0/drivers/video/logo/logo_linux_clut224.c in package linux-fslc-imx-src contains reference to TMPDIR [buildpaths]
ERROR: core-image-minimal-1.0-r0 do_rootfs: Manifest /home/proxmox/fsl-community-bsp/build/tmp/sstate-control/manifest-x86_64_x86_64-nativesdk-lib32-wayland-protocols.package_write_rpm not found in imx8dx_mek cortexa35-mx8 armv7at2hf-neon armv7ahf-neon armv7at2hf-vfp armv7ahf-vfp armv6thf-vfp armv6hf-vfp armv5tehf-vfp armv5ehf-vfp armv5thf-vfp armv5hf-vfp allarch x86_64_x86_64-nativesdk (variant 'lib32')?
ERROR: Logfile of failure stored in: /home/proxmox/fsl-community-bsp/build/tmp/work/imx8dx_mek-fslc-linux/core-image-minimal/1.0-r0/temp/log.do_rootfs.3576749
ERROR: Task (/home/proxmox/fsl-community-bsp/sources/poky/meta/recipes-core/images/core-image-minimal.bb:do_rootfs) failed with exit code '1'
NOTE: Tasks Summary: Attempted 5093 tasks of which 1977 didn't need to be rerun and 1 failed.
NOTE: Writing buildhistory
NOTE: Writing buildhistory took: 9 seconds

Summary: 1 task failed:
  /home/proxmox/fsl-community-bsp/sources/poky/meta/recipes-core/images/core-image-minimal.bb:do_rootfs
Summary: There were 2 WARNING messages.
Summary: There was 1 ERROR message, returning a non-zero exit code.

```

With my fix rebased on head of master meta-freescale, the next rebuild is successful.

2022-10-05 16:20 UTC, merged

2022-10-05 16:20 UTC, otavio commented
I could reproduce it using the wayland-protocols lib.