musl fixes
Freescale/meta-freescale pull request #1214
Opened 2022-09-17 17:05 UTC by kraj

2022-09-17 17:23 UTC, otavio approved these changes

2022-09-17 19:01 UTC, otavio requested changes

2022-09-17 19:01 UTC, otavio commented on recipes-graphics/imx-g2d/imx-dpu-g2d_2.1.0.bb
> +
Please make sure this is consistent on every recipe (close to the end of the recipe and without newlines).

2022-09-18 01:11 UTC, kraj commented
Cool, now I have `yoe-ptest-image` with weston running with musl on a `imx8qm-variscite-som` box

2022-09-18 19:16 UTC, otavio approved these changes

2022-09-19 20:35 UTC, kraj commented on recipes-graphics/xwayland/xwayland_%.bbappend
> +LDFLAGS:append:imxgpu:libc-musl = " -Wl,--allow-shlib-undefined"
Are there machines which are just imxgpu and not 3D ? The second one covers those

2022-09-19 20:52 UTC, thochstein commented on recipes-graphics/xwayland/xwayland_%.bbappend
> +LDFLAGS:append:imxgpu:libc-musl = " -Wl,--allow-shlib-undefined"
Yes, they are `imxgpu:imxgpu2d`. So `imxgpu` override is sufficient and you can drop the `imxgpu3d` override.

2022-09-19 22:31 UTC, otavio approved these changes

2022-09-20 00:27 UTC, thochstein approved these changes

2022-09-20 19:05 UTC, angolini approved these changes

2022-09-20 23:51 UTC, merged