conf: set the list of required layers
Freescale/meta-freescale pull request #1543
Opened 2023-05-23 08:19 UTC by tprrt

LAYERDEPENDS Lists the layers on which this recipe depends.

meta-oe is required by the linux-fscl recipe because it depends of lzop-native.

2023-05-23 11:29 UTC, otavio requested changes

2023-05-23 11:29 UTC, otavio commented on conf/layer.conf
> +LAYERDEPENDS_freescale-layer = "core openembedded-layer"
Hello! I was wondering if I could make a request regarding `linux-fslc`. Is it possible to take out the need for `lzop-native` and make `meta-oe` something that isn't required? If it's not too much trouble, could you create a PR for this? Thank you so much!

2023-05-23 17:52 UTC, otavio commented on conf/layer.conf
> +LAYERDEPENDS_freescale-layer = "core openembedded-layer"
Please check #1544.

2023-05-24 12:32 UTC, tprrt commented on conf/layer.conf
> +LAYERDEPENDS_freescale-layer = "core"
Done, sorry for forgetting.

2023-05-24 12:37 UTC, merged