keyctl-caam: add keyctl-caam recipe from meta-imx
Freescale/meta-freescale pull request #1545
Opened 2023-05-24 16:55 UTC by EstebanSannin

This recipe comes from [meta-imx](https://github.com/nxp-imx/meta-imx/blob/kirkstone-5.15.71-2.2.0/meta-bsp/recipes-security/smw/keyctl-caam_git.bb).

keyctl-caam (the binary name is `caam-keyctl`) is a tool useful to implement use cases like encrypted storage using CAAM secure keys as described in the NXP Application note AN12714.

2023-05-24 17:07 UTC, otavio requested changes
I did some minor comments. Also, commit log should be: `keyctl-caam: xxx`.

2023-05-24 17:07 UTC, otavio commented on recipes-security/swm/keyctl-caam_git.bb
> +COMPATIBLE_MACHINE = "(imx-nxp-bsp)"
`imx-generic-bsp`

2023-05-24 17:07 UTC, otavio commented on recipes-security/swm/keyctl-caam_git.bb
> +}
Isn't this the default?

2023-05-24 17:07 UTC, otavio commented on recipes-security/swm/keyctl-caam_git.bb
> +SRC_URI = "${KEYCTL_CAAM_SRC};branch=${SRCBRANCH}"
avoid indirections in the SRC_URI

2023-05-24 23:38 UTC, otavio approved these changes

2023-05-24 23:38 UTC, merged

2023-05-25 17:07 UTC, thochstein commented
Should this have been on `master` first?

2023-05-25 17:34 UTC, otavio commented
Sure, my fault. I'll apply it.

2023-05-25 17:38 UTC, otavio commented
https://github.com/Freescale/meta-freescale/commit/617d50bebb3bec40c58efd256df63fa2e9fa69cb applied.