gstreamer1.0-plugins-base: Fix GL packageconfig and Vivante GPU details
Freescale/meta-freescale pull request #1596
Opened 2023-07-04 20:18 UTC by dv1

* Extract PACKAGECONFIG_GL settings into a common .bappend file that is used for both the imx GStreamer fork and upstream GStreamer.
* Backport fix for being able to use the viv-fb display support in upstream GStreamer (relevant for i.MX6).
* Backport fix for decoupling Vivante direct textures from the viv-fb display support, since direct textures can also be used with other systems like Wayland for example. This obviates the need to enable the viv-fb package just to get "fast paths" in GStreamer pipelines; if direct textures are supported, they are enabled automatically.

2023-07-05 14:19 UTC, otavio requested changes

2023-07-05 14:45 UTC, thochstein commented on recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.22.%.bbappend
> +            file://0002-gl-Separate-viv-direct-texture-checks-from-viv-fb-wi.patch"
Yes, sounds good

2023-07-09 16:24 UTC, dv1 commented
I'd wait for 1.22.5 to get released, then I'd upgrade the copy in OE-core git master. That's because [the direct texture check patch was backported to 1.22](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/4959). The viv-fb patch was [reverted upstream](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/4657) due to build errors that happened in certain cases, and then got obsoleted by [a newer approach](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/4626), which needs more testing. I'll try that one out, then add it as a backported patch to OE-core.

2023-09-14 09:35 UTC, dv1 commented
@otavio @thochstein I updated the changes after GStreamer 1.22.5 became available in OE-core. (1.22.5 brings essential fixes for how viv-fb is handled.) Extra patches are no longer needed - it is purely about adjusting `PACKAGECONFIG_GL` now. I set up everything such that `PACKAGECONFIG_GL` essentially stays the same for the 1.22.0.imx recipe, while the upstream recipe gets `viv-fb` added only in vendor imx6 BSPs.

2023-09-14 09:37 UTC, dv1 commented on recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.22.%.bbappend
> +            file://0002-gl-Separate-viv-direct-texture-checks-from-viv-fb-wi.patch"
This is obsoleted by GStreamer 1.22.5 and the updated version of the MR.

2023-09-14 12:34 UTC, otavio approved these changes

2023-09-14 15:05 UTC, merged