recipes-multimedia: Update for NXP release 6.1.55-2.2.0
Freescale/meta-freescale pull request #1750
Opened 2024-02-08 21:14 UTC by valijec

Upgraded:
 - gstreamer1.0-plugins-bad:     1.22.0 -> 1.22.5
 - gstreamer1.0-plugins-base:    1.22.0 -> 1.22.5
 - gstreamer1.0-plugins-good:    1.22.0 -> 1.22.5
 - gstreamer1.0:                 1.22.0 -> 1.22.5
 - imx-codec:                    4.8.1 -> 4.8.2
 - imx-dsp:                      2.1.5 -> 2.1.6
 - imx-dsp-codec-ext:            2.1.5 -> 2.1.6

Updated:
 - imx-alsa-plugins_git.bb
 - imx-gst1.0-plugin_git.bb
 - imx-vpuwrap_git.bb
 - imx-parser_4.8.1.bb

New feature:
 - imx-opencl-converter_0.1.bb

2024-02-08 21:16 UTC, valijec commented
Fixes issue [#1715](https://github.com/Freescale/meta-freescale/issues/1715)

2024-02-09 15:28 UTC, thochstein requested changes
There are some other changes in meta-imx that we might need, like `pipewire`

2024-02-09 15:28 UTC, thochstein commented on recipes-multimedia/imx-parser/imx-parser_4.8.1.bb
Version needs to be updated

2024-02-09 19:17 UTC, MrCry0 approved these changes

2024-02-12 10:14 UTC, valijec commented on recipes-multimedia/gstreamer/imx-gst1.0-plugin_git.bb
>  LIC_FILES_CHKSUM = "file://LICENSE.txt;md5=fbc093901857fcd118f065f900982c24"
> Please move this assignment under the `LICENSE` assignment
Thank you, done :)

2024-02-12 14:39 UTC, merged

2024-02-12 14:47 UTC, valijec commented
> There are some other changes in meta-imx that we might need, like `pipewire`

Thank you @thochstein I will investigate and I'll open a new PR if it needs to be added