Upgrade graphics to LF 6.6.23-2.0.0
Freescale/meta-freescale pull request #1875
Opened 2024-07-26 16:30 UTC by valijec

Upgrade graphics to LF 6.6.23-2.0.0:
- weston: Upgrade from 12.0.3 to 12.0.4
- wayland-protocols: Replace hardcoded SRC_URI with WAYLAND_PROTOCOLS_SRC variable
- mesa-demos: Add patch for egl clear backgrounds black color
- mesa: Add patches for video showing wrong frame and fix virgl driver assert issue
- imx-gpu-viv: Upgrade from 6.4.11.p2.4-* to 6.4.11.p2.6-*
- imx-dpu-g2d: Upgrade imxdpu-g2d from 2.1.12 to 2.1.14
- imx-gpu-g2d: Upgrade from 6.4.11.p2.4 to 6.4.11.p2.6
- imx-g2d-samples: Update to latest 431f311a
- imx-pxp-g2d: Update to latest edd234c4e

2024-07-27 09:05 UTC, MaxKrummenacher commented
Hi
Thanks for the patches.

I think the change to the `wayland imx` should go into its own recipe. The change is unrelated to the `weston imx` update.

Additionally I would reword the weston patch to make it clear it is about the imx fork, e.g. `weston: Upgrade from 12.0.3.imx to 12.0.4.imx`

2024-07-29 17:47 UTC, MaxKrummenacher commented
Looks good to me.

2024-07-30 07:21 UTC, valijec commented
Thank you @MaxKrummenacher I rebased the branch to include latest commits from [Freescale:master](https://github.com/Freescale/meta-freescale/tree/master)

2024-07-30 19:03 UTC, angolini commented
I think this merge should wait the linux-imx bump. Other than that I think it's ok

2024-08-06 22:38 UTC, otavio requested changes

2024-08-06 22:38 UTC, otavio commented on recipes-graphics/imx-g2d/imx-gpu-g2d_6.4.11.p2.6.bb
> +# Copyright 2017-2022 NXP
Keep old date.

2024-08-07 21:49 UTC, thochstein commented on recipes-graphics/imx-g2d/imx-dpu-g2d_2.1.14.bb
> +
Good, it looks like I accidentally removed this in the last update.

2024-08-07 21:53 UTC, thochstein approved these changes

2024-08-08 11:04 UTC, otavio commented
Good, just squash the change in the previous commit and push it again to the branch, so I can merge it.

2024-08-08 11:18 UTC, valijec commented
> Good, just squash the change in the previous commit and push it again to the branch, so I can merge it.

Done, sorry for that, now should be ok

2024-08-08 11:26 UTC, merged