imx-cst: introduce the recipe for the version 3.4.0
Freescale/meta-freescale pull request #1905
Opened 2024-08-23 09:29 UTC by tq-gerberp

New version of NXP i.MX Code Signing Tool for signing images for i.MX HABv4 and AHAB.

2024-08-23 14:21 UTC, otavio requested changes
Please remove the old recipe so we just maintain one version of it.

2024-08-27 06:07 UTC, tq-gerberp commented
Removed old recipe and updated commit description.

2024-08-27 10:44 UTC, MrCry0 approved these changes

2024-08-27 12:05 UTC, merged

2024-08-27 12:42 UTC, tq-gerberp commented
Thanks for merging. Backport to Scarthgap could be useful to support HAB for i.MX9.