machines: imx-base.inc: fix failing u-boot builds
Freescale/meta-freescale pull request #614
Opened 2021-01-25 16:30 UTC by MaxKrummenacher

CC @thochstein

2021-01-25 18:12 UTC, otavio requested changes
Thanks @MaxKrummenacher for the fix. I agree with the fix and thinking deeper about the issue, I think we ought to remove the hack as you did and move this to `fsl-base` distro, where it belongs.

Could you rework this PR and prepare a new one for meta-freescale-distro?

2021-01-25 18:29 UTC, MaxKrummenacher commented
@otavio 
I can try to do so. E.g. move the
```
# u-boot-imx does not use a SPL
UBOOT_MAKE_TARGET_fsl = "u-boot.imx"
UBOOT_SUFFIX_fsl = "imx"
SPL_BINARY_fsl = ""
WKS_FILE_fsl = "imx-uboot-bootpart.wks.in"
```
to fsl-base.conf.

The used defconfig is a combination of machine and u-boot recipe so that I think this would need to stay in the <machine>.conf, rather than having a machine specific override in the distro.
However I'm unsure if this is really a better solution. It distributes the U-Boot configuration even further. And, more importantly if u-boot-imx should decide to move to a SPL solution for some machines for others not then the SPL <machine>.conf would again have to override the override from fsl-base or move the definition of the variables yet again.

What do you think?

2021-01-26 09:16 UTC, MaxKrummenacher commented
This is how it looks with the changes moved to the distro. Needs also https://github.com/Freescale/meta-freescale-distro/pull/46.

2021-01-26 11:24 UTC, otavio approved these changes

2021-01-26 11:24 UTC, merged