opencv_4.4.0.imx: add recipe
Freescale/meta-freescale pull request #667
Opened 2021-02-26 19:50 UTC by chrisdimich

Add recipe to support additional machine learning demos and tiny dnn.

2021-02-26 20:09 UTC, otavio requested changes
Awesome, however we need to add the preferences and compatibility here otherwise it'll have multiple providers for it.

2021-02-26 20:12 UTC, chrisdimich commented
Right, as we discussed I was going to add that to imx-base.inc, but was waiting for this to be pushed first. Let me add that to this PR.

2021-02-26 21:36 UTC, otavio commented on recipes-support/opencv/opencv_4.4.0.imx.bb
> +########## End of i.MX overrides ##########
We need to restrict the recipe to mx8.

2021-03-01 23:59 UTC, chrisdimich commented
@otavio gentle reminder :) I made the change you requested and restricted recipe to mx8 only.

2021-03-02 00:06 UTC, otavio commented on recipes-support/opencv/opencv_4.4.0.imx.bb
> +########## End of i.MX overrides ##########
This commit belongs to the recipe patch, not the `imx-base.inc`.

2021-03-02 21:24 UTC, chrisdimich commented
@otavio I split the commits. Is this all good now?

2021-03-02 21:34 UTC, otavio approved these changes

2021-03-02 21:34 UTC, merged