Add 8M Plus EVK with DDR4
Freescale/meta-freescale pull request #701
Opened 2021-03-29 17:47 UTC by thochstein

2021-03-29 18:03 UTC, otavio requested changes
Please add the ddr4 variant here as well.

2021-03-29 18:16 UTC, thochstein commented
> Please add the ddr4 variant here as well.

Do you mean you want me to squash the 2 commits?

2021-03-29 18:25 UTC, otavio commented
When I saw it, it didn't have the ddr4 variant. I think it is fine in two commits.

2021-03-30 11:53 UTC, angolini approved these changes

2021-03-30 11:55 UTC, merged